image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python3 -m safety check
          - python3 -m bandit -r serverchecks
          - pipe: snyk/snyk-scan:0.2.0
            variables:
              SNYK_TOKEN: $SNYK_TOKEN
              LANGUAGE: "python-3"
